spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=Qwery@jimi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#ログファイルに出力する設定
#logging.file.name=logs/app.log
#ログファイルのローテーション設定
#logging.logback.rollingpolicy.max-history=2